### ISSUE TITLE
clang-40 build on FreeBSD fails: undefined reference to `dorglq_'

### ISSUE THREAD

**Issue by yurivict** [SebWouters/CheMPS2#62]
Build fails:

```
libchemps2.so.2: undefined reference to `dorglq_'
libchemps2.so.2: undefined reference to `dgemm_'
libchemps2.so.2: undefined reference to `daxpy_'
libchemps2.so.2: undefined reference to `dlasrt_'
libchemps2.so.2: undefined reference to `dgesdd_'
libchemps2.so.2: undefined reference to `dsyev_'
libchemps2.so.2: undefined reference to `dlange_'
libchemps2.so.2: undefined reference to `dcopy_'
libchemps2.so.2: undefined reference to `dscal_'
libchemps2.so.2: undefined reference to `dgelqf_'
libchemps2.so.2: undefined reference to `ddot_'
libchemps2.so.2: undefined reference to `dorgqr_'
libchemps2.so.2: undefined reference to `dgeqrf_'
libchemps2.so.2: undefined reference to `dgemv_'
libchemps2.so.2: undefined reference to `dlansy_'
```

**Comment by loriab** [comment]
Sorry, you can't escape me on GH this weekend, it seems, @yurivict. It looks like lapack isn't getting linked in properly. The latest commit to this repo has some additional notes. If it's helpful, my packaging scripts are [here](https://github.com/psi4/psi4meta/blob/master/conda-recipes/chemps2/build.sh).

**Comment by yurivict** [comment]
This is because cmake fails to find lapack.

I use openblas and have to supply ```CMAKE_ARGS+=-DLAPACK_LIBRARIES="-lopenblas"```, otherwise it can't find it.

**Comment by loriab** [comment]
Yes, the usual CMake `find_package(LAPACK)` didn't work with OpenBLAS [until CMake 3.6](https://stackoverflow.com/a/38398044), so it's possibly not surprising you had to seed your build.

This incomplete LAPACK support is part of the reason Psi uses more sophisticated math detection internally, then conveys that library/header configuration through the TargetLAPACK files that trouble you.

**Comment by yurivict** [comment]
There are also several LAPACK implementations that can be installed at the same time. It isn't clear how can cmake even decide which one to use.
